### PR TITLE
Fix problem in compact mode

### PR DESCRIPTION
**Pull request by cpascual**
This is my proposed solution to https://github.com/cpascual/taurus/pull/5#issuecomment-223510738

### CODE REVIEW

**Comment by vxgmichel** [comment]
Isn't it a bit too forgiving? As I said in my comment, it seems to be related to definition of read/write widgets. Isn't it better to assume than a read widget inherits from `TaurusBaseWidget` and a write widget from `TaurusBaseWritableWidget`?

**Comment by cpascual** [comment]
I considered that option too, but I think it is too limiting. The case of the launcher buttons is a good example of a widget that makes no sense as a `TaurusBaseWritableWidget` yet it makes sense as a write widget in a `TaurusValue`. Similarly, I am sure some people may want to use some  non-taurus widgets as write widgets in some situations.

Also, on weighting the pro's and con's of this solution, I considered that the set of triggers we are setting by default are just a "scattershot" and it is ok if some of them do not work for certain widgets (as long as they are not harmful). In fact the situation in Taurus 3.x is just that (the signal is connected but never emitted).

But my preference is not strong on this. If the previous arguments do not convince you, my second option would be to implement the `applied` signal in the `TaurusLauncherButton` class, with a default implementation more or less like this:

``` python
class TaurusLauncherButton(...):
    applied = Qt.pyqtSignal()
    widgetAppliedSigName = ''
     ...
    def createWidget(self):
        ...
        widgetAppliedSig = getattr(widget, widgetAppliedSigName, None)
        if widgetAppliedSig is not None:
            widgetAppliedSig.connect(self.applied)
```

**Comment by vxgmichel** [comment]
OK that makes sense! ;)

**Comment by cpascual** [comment]
Hi,

It looks like I made a mistake and made the pull request to your develop branch, instead of the bug-187 branch.

Could you please apply the commit to the bug-187 branch instead?

(sorry for the mess-up)

**Comment by vxgmichel** [comment]
I should have paid more attention! Done!

**Pull request merged**
